### ISSUE TITLE
I'm sure I'm missing something but...

### ISSUE THREAD

**Issue by GwynethLlewelyn** [OwO-Network/gDeepLX#4]
... where exactly do you put your DeepL API key?

Also, I cannot see any reference to the endpoint you're using.

It _seems_ to me that you're just basically emulating a request coming from the iOS app, directly to DeepL's own servers, therefore bypassing all of their public API. Is that so?

Because otherwise there should be some obvious place to put one's API credentials. Unless these are supposed to be some environment keys (but the code doesn't seem to need/want any).

**Comment by missuo** [comment]
As you said, this project simulates the requests of the DeepL iOS client, so you don't need any API Key.

**Comment by GwynethLlewelyn** [comment]
Thank you! I thought as much. Nice overall work, BTW :)
