### ISSUE TITLE
Alternative Words doesn't work no matter what data is given

### ISSUE THREAD

**Issue by gi-yt** [OwO-Network/gDeepLX#5]
While I get alternative words for EN->FR with text "Hello" on deepl.com/translator, no alternative words are available in the interface returned by gDeepLX.

After a bit of digging, it seems like the jsonrpc method used by the web ui and gdeeplx is different (LMT_handle_jobs in webui vs LMT_handle_texts in gdeeplx), and their data structure is almost completely different as well.

**Comment by missuo** [comment]
The current code is designed based on iOS App.
